spring:
    profiles:
        active:
            - dev
    application:
        name: catalog-service

    data:
        mongodb:
          database: catalog
          uri: mongodb://localhost:27017/catalog
    server:
        port: 8084
