spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: root1234
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.5
          max-interval: 10000


server:
  port: 8081
  servlet:
    context-path: /profile

producer-service:
  domain: identity
  name: identity-service
  event:
    created: created
    updated: updated
    deleted: deleted

identity-service:
  identity:
    created:
      queue: identity-service.identity.created.queue
    updated:
      queue: identity-service.identity.updated.queue
    deleted:
      queue: identity-service.identity.deleted.queue

eureka:
  client:
    eureka-server-port: 8761